import React, { useEffect, useState } from 'react';
import './DataSourcesPage.css';

const DataSourcesPage: React.FC = () => {
  const [documents, setDocuments] = useState<{ license: string; notice: string } | null>(null);
  const [failed, setFailed] = useState(false);
  useEffect(() => {
    const controller = new AbortController();
    // Display the distributed legal documents themselves so the disclosure
    // cannot silently diverge from the licence shipped alongside the model.
    const read = async (name: string) => {
      const response = await fetch(`/models/spl-nac/${name}`, { signal: controller.signal });
      if (!response.ok) throw new Error('Document unavailable');
      return response.text();
    };
    Promise.all([read('LICENSE.txt'), read('NOTICE.md')])
      .then(([license, notice]) => setDocuments({ license, notice }))
      .catch(() => { if (!controller.signal.aborted) setFailed(true); });
    return () => controller.abort();
  }, []);

  return (
    <main className="data-sources-page" aria-labelledby="data-sources-title">
      <div id="data-sources" className="data-sources-content">
        <p className="data-sources-eyebrow">ABOUT MAPPED</p>
        <h1 id="data-sources-title">Data sources & licences</h1>
        <p>MAPPED uses third-party anatomical reference data. Learn where each model comes from, how we have adapted it, and which terms apply to its use.</p>
        <nav aria-label="Data sources on this page"><a href="#spl-source">SPL/NAC</a><a href="#allen-source">Allen</a><a href="#mni-source">MNI reference</a></nav>

        <section id="spl-source" aria-labelledby="spl-title">
          <span className="data-sources-badge">Default bilateral model</span>
          <h2 id="spl-title">SPL/NAC Brain Atlas</h2>
          <p>Released in January 2017 by the Open Anatomy Project. Developed through a collaboration between Brigham and Women’s Hospital and Massachusetts General Hospital, using MRI scans of a healthy 42-year-old male volunteer. Automated labelling was followed by manual segmentation of many structures.</p>
          <dl><dt>In MAPPED</dt><dd>233 selected brain surfaces, including 109 labelled left and 109 labelled right structures, and 15 other structures. Both hemispheres are from the source data.</dd><dt>Adaptations</dt><dd>Converted VTK surfaces to GLB, rotated coordinates for the viewer, and recomputed normals. No mirroring or decimation. Original MRI volumes and external head structures are not included.</dd><dt>Licence</dt><dd>3D Slicer Contribution and Software License Agreement, version 1.0 (20 December 2005), Part B.</dd><dt>Use and redistribution</dt><dd>The licence permits royalty-free use, modification, display, redistribution, and inclusion in proprietary products, subject to its conditions. Preserve notices and applicable licences, identify modifications, and do not imply institutional endorsement. Publication of modifications as open source is optional.</dd></dl>
          <p>Authors: Michael Halle, Florin Talos, Marianna Jakab, Nikos Makris, Dominic Meier, Laurence Wald, Bruce Fischl, and Ron Kikinis. Additional contributors and funding acknowledgements appear in the distributed notice below.</p>
          <div className="data-sources-links"><a href="https://www.openanatomy.org/atlas-pages/atlas-spl-nac-brain.html">Original atlas and contributors ↗</a><a href="/models/spl-nac/NOTICE.md">Download attribution notice</a><a href="/models/spl-nac/LICENSE.txt">Full licence text</a><a href="/models/spl-nac/manifest.json">Conversion provenance</a></div>
          <p>All or portions of this licensed product (such portions are the “Software”) have been obtained under license from The Brigham and Women’s Hospital, Inc. and are subject to the following terms and conditions:</p>
          {failed && <p role="alert">The inline documents could not be loaded. Use the full licence and attribution links above.</p>}
          {!documents && !failed && <p role="status">Loading licence and attribution…</p>}
          {documents && <><details><summary>Read the full licence agreement</summary><pre>{documents.license}</pre></details><details><summary>Read attribution and modification notices</summary><pre>{documents.notice}</pre></details></>}
        </section>

        <section id="allen-source" aria-labelledby="allen-title">
          <span className="data-sources-badge">Archived original atlas</span>
          <h2 id="allen-title">Allen Human Reference Atlas — 3D, 2020</h2>
          <p>A 141-structure adult human brain parcellation drawn on the ICBM 2009b nonlinear symmetric reference volume. The original Allen model is archived for possible future use. Research saved against its structure identifiers is retained; the model can be restored by the project maintainer.</p>
          <dl><dt>Source version</dt><dd>1.0.0 · RRID: SCR_017764 · © 2019 Allen Institute for Brain Science.</dd><dt>Adaptations</dt><dd>Distributed as GLB meshes with region metadata for selection, filtering, and research links. This is a processed model, not the original annotation volume. The complete historical mesh-export procedure has not yet been verified.</dd><dt>Licence</dt><dd>Creative Commons Attribution 4.0 International (CC BY 4.0), effective for these materials from 1 September 2022.</dd><dt>Use and redistribution</dt><dd>Commercial use and adaptation are permitted. Provide attribution, retain relevant notices, link to the licence, indicate changes, and avoid additional restrictions on the licensed material. Attribution does not imply endorsement.</dd></dl>
          <p className="data-sources-citation">Song-Lin Ding, Joshua J. Royall, Susan M. Sunkin, Benjamin A.C. Facer, Phil Lesnar, Amy Bernard, Lydia Ng, and Ed S. Lein (2020). Allen Human Reference Atlas — 3D, 2020. RRID: SCR_017764, version 1.0.0. Allen Institute for Brain Science.</p>
          <div className="data-sources-links"><a href="https://download.alleninstitute.org/informatics-archive/allen_human_reference_atlas_3d_2020/version_1/">Original dataset ↗</a><a href="https://download.alleninstitute.org/informatics-archive/allen_human_reference_atlas_3d_2020/version_1/README.pdf">Dataset documentation ↗</a><a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0 licence ↗</a><a href="https://alleninstitute.org/legal/citation-policy/">Citation policy ↗</a></div>
        </section>

        <section id="mni-source" aria-labelledby="mni-title">
          <span className="data-sources-badge">Reference underlying the Allen atlas</span>
          <h2 id="mni-title">ICBM 152 nonlinear reference templates — 2009</h2>
          <p>Population-average MRI templates from the McConnell Brain Imaging Centre, Montreal Neurological Institute, McGill University. The Allen parcellation uses the ICBM 2009b nonlinear symmetric reference. MAPPED does not present this as a separate selectable model or claim to distribute the original MRI volume.</p>
          <p>The source permits use, copying, modification, and distribution for any purpose without fee, provided its copyright notice appears in all copies. It is supplied without warranty.</p>
          <p>Copyright © 1993–2004 Louis Collins, McConnell Brain Imaging Centre, Montreal Neurological Institute, McGill University.</p>
          <p className="data-sources-citation">Fonov VS, Evans AC, Botteron K, Almli CR, McKinstry RC, Collins DL, and BDCG (2011). Unbiased average age-appropriate atlases for pediatric studies. NeuroImage 54(1). DOI: 10.1016/j.neuroimage.2010.07.033.<br />Fonov VS, Evans AC, McKinstry RC, Almli CR, and Collins DL (2009). Unbiased nonlinear average age-appropriate brain templates from birth to adulthood. NeuroImage 47, Supplement 1, S102. DOI: 10.1016/S1053-8119(09)70884-5.</p>
          <div className="data-sources-links"><a href="https://nist.mni.mcgill.ca/icbm-152-nonlinear-atlases-2009/">Template documentation and licence ↗</a></div>
        </section>

        <section aria-labelledby="head-preview-title"><h2 id="head-preview-title">Experimental SPL head-and-neck layers</h2><p>The optional Explorer preview contains a skull, mandible, and bilateral common, internal and external carotid arteries, vertebral arteries, and internal jugular veins. These come from a separate MANIX CT acquisition, not the SPL/NAC brain subject. They do not provide a complete intracranial arterial tree or meninges.</p><p>MAPPED converted twelve VTK surfaces to GLB and applied a shared experimental CT-to-MRI affine fit, including nonuniform scaling, before the viewer rotation. The fit has not been validated against independent landmarks or accepted by an anatomical reviewer. These layers are an illustrative preview.</p><p>Authors: Marianna Jakab and Ron Kikinis, Surgical Planning Laboratory, Brigham and Women’s Hospital. Contributor and funding notices are included below. The source page states September 2015; the downloaded archive is identified as head-neck-2016-09. The source identifies the 3D Slicer licence, Part B, whose full terms are reproduced above; the same terms apply to these distributed assets.</p><p>All or portions of this licensed product (such portions are the “Software”) have been obtained under license from The Brigham and Women’s Hospital, Inc. and are subject to the following terms and conditions:</p><div className="data-sources-links"><a href="https://www.openanatomy.org/atlas-pages/atlas-spl-head-and-neck.html">Original head-and-neck atlas ↗</a><a href="/models/spl-head-neck/LICENSE.txt">Full head-layer licence</a><a href="/models/spl-head-neck/NOTICE.md">Contributors and modifications</a><a href="/models/spl-head-neck/experimental-registration.json">Experimental alignment provenance</a></div></section>
        <section aria-labelledby="vessel-check-title"><h2 id="vessel-check-title">Vessel validation status</h2><p>Checks on 5 October 2026 confirmed that all ten vessels exactly preserve the original source vertices and triangle connectivity. The left common carotid's two small fragments and topology irregularities in the right internal carotid and left vertebral artery are inherited from the source. Surface samples agree with the published CT labels within approximately two millimetres; this is source agreement, not independent anatomical validation.</p><p>A gross alignment screen found 121 sampled brain vertices more than 2 mm inside the fitted skull's voxel-centre bone boundary, with a maximum sampled depth of 3.91 mm in source CT space. The current cross-subject fit is not accepted as anatomically validated. These samples do not measure overlap volume or anatomical accuracy. Complete vessel courses and target-brain placement still require independent image, landmark and expert review.</p><div className="data-sources-links"><a href="/models/spl-head-neck/vessel-source-review.json" target="_blank" rel="noreferrer">Source and alignment report</a><a href="/models/spl-head-neck/vessel-source-review.png" target="_blank" rel="noreferrer">Flagged vessels on source CT</a><a href="/models/spl-head-neck/brain-skull-collision-review.png" target="_blank" rel="noreferrer">Brain–skull overlap evidence</a><a href="/models/spl-head-neck/vessel-validation.json" target="_blank" rel="noreferrer">Initial mesh audit</a></div></section>
        <section aria-labelledby="central-artery-title"><h2 id="central-artery-title">BodyParts3D central arterial preview</h2><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International. The optional preview contains 18 elements: bilateral ACAs, MCA M1 and selected M2 parts, PCA P1/P2 parts, posterior communicating arteries, internal carotids, an anterior communicating artery and one basilar representation. These are atlas representations, including symmetric bilateral geometry, rather than verified vessels from the SPL/NAC subject.</p><p>MAPPED used the official 4.0 IS-A 99%-reduced OBJ archive, triangulated the selected surfaces, regenerated normals and applied one shared experimental similarity fit using five matching brain-structure centre proxies. The fit was refined with labelled surface matching on 6 October 2026. Withheld hippocampal median surface differences improved from 4.6–5.0 mm to 3.7–3.8 mm; 95th percentiles improved from 10.1–10.8 mm to 8.8–9.3 mm. These are reference-atlas surface checks, not vessel registration errors. Mesh proximity does not prove a connected lumen or complete Circle of Willis. Fine branches, anatomical placement and connections to the separately fitted skull/neck atlas remain unvalidated. No endorsement is implied.</p><p>The current official database licence page, updated 27 February 2025, states CC BY 4.0. The source OBJ headers retain older CC BY-SA 2.1 Japan notices; source bytes and provenance are preserved in the workbench.</p><div className="data-sources-links"><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html">Original dataset</a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html">Official licence</a><a href="https://creativecommons.org/licenses/by/4.0/legalcode">Full CC BY 4.0 terms</a><a href="/models/bodyparts3d-central/NOTICE.md">Attribution & modifications</a><a href="/models/bodyparts3d-central/coverage-and-alignment.json">Structure coverage & alignment checks</a></div></section>
        <section aria-labelledby="meningeal-title"><h2 id="meningeal-title">Z-Anatomy dural folds and venous sinuses</h2><p>Z-Anatomy — The open source atlas of anatomy — CC BY-SA 4.0. BodyParts3D — The Database Center for Life Science — CC BY-SA 2.1 Japan, as credited by this derivative collection. The optional layer contains falx cerebri, bilateral tentorium and sixteen named dural venous-sinus objects. It does not include an outer cranial dura shell, arachnoid or pia membrane. Empty confluence/helper objects are excluded.</p><p>MAPPED preserved FBX world transforms, selected specific fold/sinus geometry, triangulated it, regenerated normals and applied one shared experimental similarity fit to matching brain-structure centre proxies. Shape-based refinement on 6 October 2026 improved withheld hippocampal median surface differences from 4.5–5.2 mm to about 3.8 mm, and 95th percentiles from 10.1–10.9 mm to 9.1–9.4 mm. These are reference-surface checks, not anatomical accuracy. Source geometry includes near-symmetric bilateral anatomy. Source topology checks flag the falx and cavernous sinuses; the original straight-sinus gaps were confirmed in the canonical Blender source. Its placement was reconstructed between the posterior inferior-sagittal end ring and source confluence annotation, preserving radial dimensions and retaining source topology. Junction vertex gaps are now approximately 0.25–1.1 mm; contact does not establish a fused lumen or validated course. These are illustrative inspection assets, not a complete connected venous system or anatomically accepted fit.</p><p>The adapted model assets are distributed under CC BY-SA 4.0 with source attribution and notices. The source collection also contains unrelated NonCommercial inner-ear/kidney assets; those were not selected. The newer BodyParts3D licence is not applied retroactively to Z-Anatomy derivatives. No endorsement is implied.</p><div className="data-sources-links"><a href="https://github.com/LluisV/Z-Anatomy/tree/PC-Version/Resources/Models">Source model files</a><a href="/models/z-anatomy-meninges/NOTICE.md">Attribution & modifications</a><a href="/models/z-anatomy-meninges/SOURCE-LICENSE.txt">Source model notices</a><a href="/models/z-anatomy-meninges/LICENSE.txt">Full ShareAlike licence</a><a href="/models/z-anatomy-meninges/coverage-and-alignment.json">Coverage & source review</a><a href="/models/z-anatomy-meninges/alignment-comparison.json">Alignment alternatives</a></div></section>
        <section aria-labelledby="limitations-title"><h2 id="limitations-title">Reference-model limitations</h2><p>These models support research and learning. They do not represent a particular user's anatomy, and MAPPED's conversions have not received independent anatomical or clinical validation. The Slicer licence states that clinical applications are not recommended or approved. No source institution endorses MAPPED.</p><p>Outer dura, arachnoid and pia membranes and fine intracranial branches remain unavailable. The current skull and vascular fits retain their warnings: tested alternatives did not establish anatomical accuracy. Any additional dataset will receive its own source, attribution, modification, and licence disclosure.</p></section>
        <p className="data-sources-updated">Disclosures reviewed 4 October 2026. The original licence terms govern the respective materials; the summaries above do not replace them.</p>
      </div>
    </main>
  );
};
export default DataSourcesPage;
